<?php

/**
 * Implements hook_schema().
 */
function ofed_vmcd_schema() {
  
}

/**
 * Implements hook_install().
 */
function ofed_vmcd_install() {
  
}

/**
 * Implements hook_uninstall().
 */
function ofed_vmcd_uninstall() {
  // Get all variables and delete it.
  $result = db_query("SELECT name FROM {variable} WHERE name LIKE 'ofed_vmcd_%'");
  foreach ($result as $record) {
    variable_del($record->name);
  }
}