<?php
/**
 * @file
 * Contains install and update functions for Openfed Workflow.
 */

use Drupal\Core\Installer\InstallerKernel;

/**
 * Implements hook_site_install_finished().
 */
function openfed_workflow_site_install_finished($install_state) {
  _openfed_workflow_initiate();
}

/**
 * Implements hook_install().
 */
function openfed_workflow_install() {
  if (!InstallerKernel::installationAttempted()) {
    _openfed_workflow_initiate();
  }
}
