<?php

/**
 * Implements hook_theme_registry_alter().
 */
function ofed_address_theme_registry_alter(&$theme_registry) {
  $mod_path = drupal_get_path('module', 'ofed_address');
  $theme_registry_copy = $theme_registry; // Munge on a copy
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $mod_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('node');
  foreach ($hooks as $h) {
    _ofed_address_insert_after_first_element($theme_registry[$h]['theme paths'], $mod_path);
  }
}

/**
 * Helper function for re-ordering arrays (needed by theme_registry_alter).
 */
function _ofed_address_insert_after_first_element(&$a, $element) {
  if (is_array($a)) {
    $first_element = array_shift($a);
    array_unshift($a, $first_element, $element);
  }
}

/**
 * Implements hook_preprocess_node().
 */
function ofed_address_preprocess_node() {
  drupal_add_js(drupal_get_path('module', 'ofed_address') . '/assets/scripts/ofed_address.js');
  drupal_add_css(drupal_get_path('module', 'ofed_address') . '/assets/styles/ofed_address.css');
}