<?php

require_once 'includes/ofed_slideshow.misc.inc';
require_once 'includes/ofed_slideshow.blocks.inc';

/**
 * Implements hook_theme_registry_alter().
 */
function ofed_slideshow_theme_registry_alter(&$theme_registry) {
  $mod_path = drupal_get_path('module', 'ofed_slideshow');
  $theme_registry_copy = $theme_registry; // Munge on a copy
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $mod_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('node');
  foreach ($hooks as $h) {
    _ofed_slideshow_insert_after_first_element($theme_registry[$h]['theme paths'], $mod_path);
  }
}

/**
 * Helper function for re-ordering arrays (needed by theme_registry_alter).
 */
function _ofed_slideshow_insert_after_first_element(&$a, $element) {
  if(is_array($a)) {
    $first_element = array_shift($a);
    array_unshift($a, $first_element, $element);
  }
}

/**
 * Implements hook_theme().
 */
function ofed_slideshow_theme($existing, $type, $theme, $path) {
  return array(
    'ofed_slideshow_block' => array(
      'variables' => array('slideshows' => null),
      'template' => 'templates/blocks/ofed_slideshow_block_content',
    ),
  );
}

/**
 * Implements hook_preprocess_node().
 */
function ofed_slideshow_preprocess_node() {
  drupal_add_library('jquery_plugin', 'cycle');
  drupal_add_js(drupal_get_path('module', 'ofed_slideshow') . '/assets/scripts/ofed_slideshow.js');
  drupal_add_css(drupal_get_path('module', 'ofed_slideshow') . '/assets/styles/ofed_slideshow.css');
}