<?php

require_once 'includes/ofed_banner.misc.inc';
require_once 'includes/ofed_banner.blocks.inc';

/**
 * Implements hook_theme_registry_alter().
 */
function ofed_banner_theme_registry_alter(&$theme_registry) {
  $mod_path = drupal_get_path('module', 'ofed_banner');
  $theme_registry_copy = $theme_registry; // Munge on a copy
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $mod_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('node');
  foreach ($hooks as $h) {
    _ofed_banner_insert_after_first_element($theme_registry[$h]['theme paths'], $mod_path);
  }
}

/**
 * Helper function for re-ordering arrays (needed by theme_registry_alter).
 */
function _ofed_banner_insert_after_first_element(&$a, $element) {
  if(is_array($a)) {
    $first_element = array_shift($a);
    array_unshift($a, $first_element, $element);
  }
}

/**
 * Implements hook_theme().
 */
function ofed_banner_theme($existing, $type, $theme, $path) {
  return array(
    'ofed_banner_block' => array(
      'variables' => array('banners' => null),
      'template' => 'templates/blocks/ofed_banner_block_content',
    ),
  );
}

/**
 * Implements hook_node_view().
 */
function ofed_banner_node_view($node, $view_mode, $langcode) {
  switch ($node->type) {
    case 'ofed_banner':
      drupal_add_library('jquery_plugin', 'cycle');
      drupal_add_js(drupal_get_path('module', 'ofed_banner') .'/assets/scripts/ofed_banner.js');
    break;
  }
}