<?php
/**
 * @file
 * list of all constant.
 */

  // REST Settings.
  define('ADDEMAR_SUBSCRIPTION_REST_URL', 'http://ws.mailing.presscenter.org/rest');
  define('ADDEMAR_SUBSCRIPTION_REST_PROFILE', 'FormWS');
  define('ADDEMAR_SUBSCRIPTION_REST_METHOD', 'formOptin');
  define('ADDEMAR_SUBSCRIPTION_REST_MESSAGE', 'Subscribe form');

  // GENERAL Settings.
  define('ADDEMAR_SUBSCRIPTION_CONTACT_GROUP_ID', 0);
  define('ADDEMAR_SUBSCRIPTION_SOURCE_MESSAGE', 'Subscribe form');
  define('ADDEMAR_SUBSCRIPTION_SUBSCRIPTION_TYPE', 0);

  // FIELDS Settings.
  define('ADDEMAR_SUBSCRIPTION_ADDEMAR_FIELDS', '');
  define('ADDEMAR_SUBSCRIPTION_PAGE_URL', 'newsletter/subscribe');
  define('ADDEMAR_SUBSCRIPTION_SUBMIT_BUTTON', 'Subscribe');

  // MESSAGE Settings.
  define('ADDEMAR_SUBSCRIPTION_MESSAGE_SUCCESS', 'Register success');
  define('ADDEMAR_SUBSCRIPTION_MESSAGE_ERROR', 'An error has occured');
