<?php

/**
 * Implement hook_menu_insert().
 */
function menu_dam_menu_insert() {
  _menu_dam_settings_alter();
}
/**
 * Implement hook_menu_update().
 */
function menu_dam_menu_update() {
  _menu_dam_settings_alter();
}
/**
 * Implement hook_menu_delete().
 */
function menu_dam_menu_delete() {
  _menu_dam_settings_alter();
}

/**
 * Alter the settings.
 * Add or edit the menu default active trail inside the settings.php
 * @return void
 */
function _menu_dam_settings_alter() {

    // Set the values who are mandatory.
    $values_mandatory = array('main-menu'); // To be sure :)
    // Get the custom menus names from the database.
    $values_from_db = array_keys(menu_get_menus(FALSE));
    // Merge the database values with the mandatory values.
    $values_merged = array_merge($values_mandatory, $values_from_db);
    variable_set('menu_default_active_menus', $values_merged);
}