<?php
/**
 * @file
 * add administration page, add every js link into head.
 */

/**
 * Implements hook_help().
 */
function waia_integration_help($path, $arg) {
  switch ($path) {
    case 'admin/help#waia_integration':
      // Return a line-break version of the module README.txt.
      return filter_filter('process', 1, NULL, file_get_contents(dirname(__FILE__) . "/README.txt"));
  }
}

/**
 * Implements hook_permission().
 */
function waia_integration_permission() {
  return array(
    'access waia_integration configuration' => array(
      'title' => t('Configure subscription form'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function waia_integration_menu() {
  $items['admin/config/services/waia_integration'] = array(
    'title'             => 'WAIA Integration',
    'description'       => 'Include WAIA Javascript.',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('waia_integration_admin'),
    'access arguments'  => array('access waia_integration configuration'),
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'includes/waia_integration.admin.inc',
  );

  return $items;
}

/** 
 * Implements hook_preprocess_html().
 */
function waia_integration_preprocess_html(&$variables) {
  $fields = variable_get('waia_integration_url', '');

  if (!empty($fields)) {
    if (!empty($field) && _waia_integration_url_exists($field)) {
      drupal_add_js(
        $field,
        array(
          'type' => 'external',
          'scope' => 'header',
          'cache' => FALSE,
          'preprocess' => FALSE,
          'every_page' => TRUE,
        )
      );
    }
  }

  if (drupal_get_http_header("status") == '404 Not Found') {
    $variables['attributes_array']['waia:error'] = 'errorpage';
    $variables['attributes_array']['waia:errorcode'] = '404';
    $variables['attributes_array']['waia:targetpage'] = url($_GET['destination']);
  }
  
  global $language;
  $variables['attributes_array']['waia:lang'] = $language->language;
}

/**
 * Check if url exist.
 */
function _waia_integration_url_exists($url) {
  $curl = curl_init();

  curl_setopt($curl, CURLOPT_URL, $url);
  curl_setopt($curl, CURLOPT_FAILONERROR, 1);

  curl_exec($curl);

  $return_code = curl_getinfo($curl, CURLINFO_HTTP_CODE);

  curl_close($curl);

  if ($return_code != 200 && $return_code != 302 && $return_code != 304) {
    return FALSE;
  }
  else {
    return TRUE;
  }
}
