<?php

/**
 * @file Add administration page, add every js link into head.
 */
// Include file(s).
include 'includes/waia_integration.misc.inc';

/**
 * Implements hook_help().
 */
function waia_integration_help($path, $arg) {
  switch ($path) {
    case 'admin/help#waia_integration':
      // Return a line-break version of the module README.txt.
      return filter_filter('process', 1, NULL, file_get_contents(dirname(__FILE__) . "/README.txt"));
  }
}

/**
 * Implements hook_permission().
 */
function waia_integration_permission() {
  return array(
    'administer waia integration' => array(
      'title' => t('Configure subscription form'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function waia_integration_menu() {
  $items['admin/config/services/waia_integration'] = array(
    'title' => 'WAIA Integration',
    'description' => 'Include WAIA Javascript.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('waia_integration_admin_form'),
    'access arguments' => array('administer waia integration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/waia_integration.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_preprocess_html().
 */
function waia_integration_preprocess_html(&$variables) {
  global $language;

  // Add the WAIA script.
  $url = variable_get('waia_script_url', '');
  if (!empty($url) && variable_get('waia_script_url_validated', FALSE)) {
    // Add js.
    drupal_add_js(
      $url, array(
      'type' => 'external',
      'scope' => 'header',
      'cache' => FALSE,
      'preprocess' => FALSE,
      'every_page' => TRUE,
      )
    );

    // Add the waia attributes.
    if (drupal_get_http_header("status") == '404 Not Found') {
      $variables['attributes_array']['waia:error'] = 'errorpage';
      $variables['attributes_array']['waia:errorcode'] = '404';
      if (!empty($_GET['destination'])) {
        $variables['attributes_array']['waia:targetpage'] = url($_GET['destination']);
      }
    }
    $variables['attributes_array']['waia:lang'] = $language->language;
  }
}

/**
 * Implement hook_cron().
 */
function waia_integration_cron() {
  // Check WAIA script URL.
  $url = variable_get('waia_script_url', '');
  if (!empty($url)) {
    _waia_integration_check_script_url($url);
  }
}