<?php

/**
 * Implements hook_block_info().
 */
function ofed_switcher_block_info() {
  $blocks = array();
  $blocks['ofed_switcher'] = array(
      'info' => t('Site/CMS Switcher'),
  );
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function ofed_switcher_block_view($delta = '') {
  $block = array();
  switch($delta) {
    case 'ofed_switcher':
      $block['subject'] = t('Site/CMS Switcher');
      $block['content'] = _ofed_switcher_contents();
      break;
  }
  return $block;
}

/**
 * Generate content for block view.
 */
function _ofed_switcher_contents() {
  drupal_add_css(drupal_get_path('module', 'ofed_switcher') . '/assets/styles/ofed_switcher.css');

  global $user;

  $user_info = '';
  $tool_links = array();

  if($user->uid != 0) {
    $role_found = FALSE;
    foreach(variable_get('ofed_switcher_roles', array(2)) as $value) {
      if(key_exists($value, $user->roles)) {
        $role_found = TRUE;
      }
    }

    if($role_found || $user->uid == 1) {
      if(variable_get('ofed_switcher_welcome', TRUE)) {
        $user_info = t("Welcome <strong>@user</strong>", array('@user' => $user->name));
      }
      if(variable_get('ofed_switcher_goto', TRUE)) {
        if(arg(0) == 'admin' || arg(0) == 'cms' || path_is_admin(current_path()) ) {
          $tool_links[] = l(t("Go to Front"), '<front>');
        }
        else {
          $tool_links[] = l(t("Go to CMS"), 'cms/dashboard');
        }
      }
      if(variable_get('ofed_switcher_profile', FALSE)) {
        $tool_links[] = l(t("My Profile"), 'users/' . $user->name);
      }
      if(variable_get('ofed_switcher_logout', TRUE)) {
        $tool_links[] = l(t("Logout"), 'user/logout');
      }
      return theme('ofed_switcher_block', array(
                  'user_info' => $user_info,
                  'user_links' => theme('item_list', array('items' => $tool_links)))
      );
    }
  }
  else {
    return '';
  }
}

/**
 * Implementation of hook_theme().
 */
function ofed_switcher_theme($existing, $type, $theme, $path) {
  return array(
      'ofed_switcher_block' => array(
          'variables' => array('user_info' => null, 'user_links' => null),
          'template' => 'templates/blocks/ofed_switcher_block_switcher'
      ),
      'ofed_dashboard_page' => array(
          'variables' => array('dashboard' => null),
          'template' => 'templates/pages/ofed_switcher_page_dashboard'
      )
  );
}

/**
 * Implements hook_menu().
 */
function ofed_switcher_menu() {
  $items['admin/openfed/ofed_switcher'] = array(
      'title' => t('Site/CMS Switcher'),
      'description' => t('Configure CMS Switcher settings.'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('ofed_switcher_admin'),
      'access arguments' => array('access ofed_switcher content'),
      'type' => MENU_NORMAL_ITEM,
  );

  $items['cms/dashboard'] = array(
      'title' => t('Dashboard'),
      'page callback' => 'ofed_switcher_dashboard',
      'page arguments' => array(''),
      'access arguments' => array('access administration pages'),
      'menu_name' => 'menu-cms-menu',
      'type' => MENU_NORMAL_ITEM,
      'weight' => -50
  );

  return $items;
}

/**
 * configuration page of the switcher module
 * return form
 */
function ofed_switcher_admin() {
  $form = array();

  $form['ofed_switcher_welcome'] = array(
      '#type' => 'checkbox',
      '#title' => t('Show Welcome user'),
      '#default_value' => variable_get('ofed_switcher_welcome', TRUE),
      '#description' => t('')
  );
  $form['ofed_switcher_goto'] = array(
      '#type' => 'checkbox',
      '#title' => t('Show go to CMS/Front link'),
      '#default_value' => variable_get('ofed_switcher_goto', TRUE),
      '#description' => t('')
  );
  $form['ofed_switcher_profile'] = array(
      '#type' => 'checkbox',
      '#title' => t('Show profil link'),
      '#default_value' => variable_get('ofed_switcher_profile', FALSE),
      '#description' => t('')
  );
  $form['ofed_switcher_logout'] = array(
      '#type' => 'checkbox',
      '#title' => t('Show logout link'),
      '#default_value' => variable_get('ofed_switcher_logout', TRUE),
      '#description' => t('')
  );

  $roles = user_roles(TRUE);

  $form['ofed_switcher_roles'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Roles'),
      '#default_value' => variable_get('ofed_switcher_roles', array(2)),
      '#options' => $roles,
      '#required' => TRUE,
      '#description' => t('Choose which role can see this block.<br>Note that only user with <em>Access administration theme</em> permission can view the the CMS dashboard'),
  );

  return system_settings_form($form);
}

/**
 * Dispaly the first page in the cms interface to manage content, user, block depending the permission
 * return string return the template content
 */
function ofed_switcher_dashboard() {
  $dashboard = array();

  // MANAGE QUICK INFO
  $dashboard['quick-info'] = theme('links__menu_quick_infos', array('links' => menu_navigation_links('menu-quick-infos')));
  
  // MANAGE CONTENT
  $dashboard['content'] = array();
  foreach(node_type_get_names() as $content_key => $content_name):
    if(user_access('create ' . $content_key . ' content')) :
      $dashboard['content'][$content_name] = array(t("Add !name", array('!name' => $content_name)) => 'node/add/' . str_replace('_', '-', $content_key) );
    endif;
  endforeach;

  // MANAGE USER
  if(user_access('administer users') || user_access('administer permissions')) :
    $dashboard['user'] = array();
    if(user_access('administer users')) {
      $dashboard['user'][t('Users')] = array(t('Add user') => 'admin/people/create');
    }
    if(user_access('administer permissions') ) {
      $dashboard['user'][t('Roles')] = array(t('Add role') => 'admin/people/roles');
      $dashboard['user'][t('Permissions')] = array(t('Configure permissions') => 'admin/people/permissions');
    }
  endif;

  // MANAGE BLOCK
  if(user_access('administer blocks')):
    $dashboard['block'] = array();
    $dashboard['block'][t('Blocks')] = array(t('Add Block') => 'admin/structure/block/add');
    if (module_exists('menu_block') ) {
      $dashboard['block'][t('Menu Blocks')] = array(t('Add Menu Block') => 'admin/structure/block/add-menu-block');
    }
    $dashboard['block'][t('Configuration')] = array(t('Configure block') => 'admin/structure/block');
  endif;

  return theme('ofed_dashboard_page', array('dashboard' => $dashboard));
}



/**
 * Implements hook_theme_registry_alter().
 */
function ofed_switcher_theme_registry_alter(&$theme_registry) {
  $mod_path = drupal_get_path('module', 'ofed_switcher');
  $theme_registry_copy = $theme_registry; // Munge on a copy
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $mod_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('node');
  foreach ($hooks as $h) {
    _ofed_page_insert_after_first_element($theme_registry[$h]['theme paths'], $mod_path);
  }
}

/**
 * Helper function for re-ordering arrays (needed by theme_registry_alter).
 */
function _ofed_switcher_insert_after_first_element(&$a, $element) {
  if(is_array($a)) {
    $first_element = array_shift($a);
    array_unshift($a, $first_element, $element);
  }
}