<?php

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function ofed_parent_block_info() {
  $blocks = array();
  $blocks['ofed_parent_name'] = array(
      'info' => t('Menu Parent Name'),
  );
  return $blocks;
}

/**
 * Implements hook_block_configure().
 *
 * This hook declares configuration options for blocks provided by this module.
 */
function ofed_parent_block_configure($delta = '') {
  $form = array();
  if($delta == 'ofed_parent_name') {
    $form['ofed_parent_name'] = array(
        '#type' => 'textfield',
        '#title' => t('Name of the parent name for the homepage'),
        '#size' => 60,
        '#default_value' => variable_get('ofed_parent_name', 'Home'),
    );
  }
  return $form;
}

/**
 * Implements hook_block_save().
 *
 * This hook declares how the configured options for a block
 * provided by this module are saved.
 */
function ofed_parent_block_save($delta = '', $edit = array()) {
  if($delta == 'ofed_parent_name') {
    variable_set('ofed_parent_name', $edit['ofed_parent_name']);
  }
  return;
}

/**
 * Implementation of hook_block_view().
 */
function ofed_parent_block_view($delta = '') {
  $block = array();
  switch($delta) {
    case 'ofed_parent_name':
      $block['subject'] = '<none>';
      $block['content'] = _ofed_parent_name_contents();
      break;
  }
  return $block;
}

/**
 * Implementation of block content
 * @return string
 */
function _ofed_parent_name_contents() {
  drupal_add_css(drupal_get_path('module', 'ofed_parent') . '/assets/css/ofed_parent.css');
  $breadcrumb = drupal_get_breadcrumb();
  $value = '';
  if(isset($breadcrumb['1'])) {
    $value = strip_tags($breadcrumb['1']);
  }
  elseif(drupal_is_front_page()) {
    $value = variable_get('ofed_parent_name', 'Home');
  }
  if($value == '') {
    return '';
  }
  else {
    return theme('ofed_parent_name', array('ofed_parent' => $value));
  }
}

/**
 * Implementation of hook_theme().
 */
function ofed_parent_theme($existing, $type, $theme, $path) {
  return array(
      'ofed_parent_name' => array(
          'variables' => array('ofed_parent' => null),
          'template' => 'templates/blocks/ofed_parent_block_name'
      ),
  );
}